/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {readFileSync} from 'node:fs';
import {dirname, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';

import {CharStream, CommonTokenStream} from 'antlr4ng';
import {describe, expect, it} from 'vitest';

import {ExpressLexer} from '../../../../src/inference_formats/express/generated/ExpressLexer.js';
import {ExpressParser} from '../../../../src/inference_formats/express/generated/ExpressParser.js';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '../../../../../..');
const pythonGeneratedDir = resolve(
  repoRoot,
  'python/a2ui_agent/src/a2ui/inference_formats/experimental/express/generated',
);

/**
 * Extracts the serialized ATN from a Python module generated by ANTLR. The
 * values sit between `def serializedATN():` and the class declaration that
 * follows it.
 */
function pythonSerializedAtn(fileName: string): number[] {
  const source = readFileSync(resolve(pythonGeneratedDir, fileName), 'utf8');
  const match = /def serializedATN\(\):([\s\S]*?)\nclass /.exec(source);
  if (!match) {
    throw new Error(`No serializedATN() found in ${fileName}`);
  }
  return (match[1].match(/-?\d+/g) ?? []).map(Number);
}

describe('generated Express parser', () => {
  // The serialized ATN decides every lexing and parsing decision. Identical
  // ATNs mean the TypeScript and Python SDKs accept exactly the same inputs and
  // build the same trees, regardless of which tool generated each one. A
  // failure here means one SDK was regenerated from a different grammar.
  it('has the same parser ATN as the Python SDK', () => {
    const expected = pythonSerializedAtn('express_parser.py');
    expect(expected.length).toBeGreaterThan(0);
    expect(ExpressParser._serializedATN).toEqual(expected);
  });

  it('has the same lexer ATN as the Python SDK', () => {
    const expected = pythonSerializedAtn('express_lexer.py');
    expect(expected.length).toBeGreaterThan(0);
    expect(ExpressLexer._serializedATN).toEqual(expected);
  });

  it('parses a program through the antlr4ng runtime', () => {
    const lexer = new ExpressLexer(
      CharStream.fromString('root = Column([title])\ntitle = Text("Hello")\n'),
    );
    const parser = new ExpressParser(new CommonTokenStream(lexer));
    parser.removeErrorListeners();

    const program = parser.program();

    expect(parser.numberOfSyntaxErrors).toBe(0);
    expect(program.statement()).toHaveLength(2);
  });

  it('reports a syntax error for malformed input', () => {
    const lexer = new ExpressLexer(CharStream.fromString('root = Column(['));
    const parser = new ExpressParser(new CommonTokenStream(lexer));
    parser.removeErrorListeners();

    parser.program();

    expect(parser.numberOfSyntaxErrors).toBeGreaterThan(0);
  });
});
